server:
  port: 8081

spring:
  application:
    name: member
  datasource:
    url: jdbc:h2:mem:~/testdb;mode=MySQL;database_to_lower=true;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
