spring:
  application:
    name: eureka-service

server:
  port: 8761
eureka:
  server:
    response-cache-update-interval-ms: 1000       # Eureka server's response cache.
  client:
    register-with-eureka: false                   # Only for local stand-alone development
    fetch-registry: false                         # Only for local stand-alone development
    service-url:
      defaultZone: http://localhost:8761/eureka   # Default value
#  instance:
#    prefer-ip-address: true                       # Use ip address instead of hostname from OS when reporting myself to eureka server

#logging:
#  level:
#    com:
#      netflix:
#        eureka: off
#        discovery: off
