server:
  port: 8082

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:h2:mem:~/testdb;mode=MySQL;database_to_lower=true;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
